//const { Router } = require('express')
const express = require('express')
const actions = require('../methods/actions')
const router = express.Router()

router.get('/',(req,res)=>{
    res.send('Hello1')
})

//add new user
router.post('/adduser',actions.addNew)
router.post('/authenticate',actions.authenticate)
router.get('/getinfo',actions.getinfo)
router.post('/getinfo1',actions.getinfo1)
router.post('/addBmi',actions.addNewBMI)
router.post('/update1',actions.update1)
router.post('/update2',actions.update2)
router.post('/addKeto',actions.addNewKETO)
router.get('/getketo',actions.getKeto)
router.post('/addVegetarian',actions.addNewVegetarian)
router.get('/getVegetarian',actions.getVegetarian)
router.post('/addNewPaleo',actions.addNewPaleo)
router.get('/getPaleo',actions.getPaleo)
router.post('/addNewRaw',actions.addNewRaw)
router.get('/getRaw',actions.getRaw)
router.post('/addNewCarb',actions.addNewCarb)
router.get('/getCarb',actions.getCarb)
router.post('/addNewSugar',actions.addNewSugar)
router.get('/getSugar',actions.getSugar)
router.post('/addDiet',actions.addDiet)
router.get('/getDiet',actions.getDiet)
router.post('/updateDiet',actions.updateDiet)
router.post('/addNewFood',actions.addNewFood)
router.get('/getCalories',actions.getCalories)
router.get('/getFats',actions.getFats)
router.get('/getProtein',actions.getProtein)
router.post('/checkDiet',actions.checkDiet)
router.post('/addNewOver',actions.addNewOver)
router.post('/addNewUnder',actions.addNewUnder)
router.post('/addNewNormal',actions.addNewNormal)
router.get('/getNormal',actions.getNormal)
router.get('/getOver',actions.getOver)
router.get('/getUnder',actions.getUnder)
router.post('/addWater',actions.addNewWater)
router.post('/updateWater',actions.updateWater)
router.post('/checkWater',actions.checkwater)

module.exports = router